---
# tasks file for ucarp

- fail:
    msg: "Failing, Require to setup ucarp__interface variable"
  when: ucarp__interface is not defined

- name: "Install ucarp"
  apt:
    name: ucarp
    state: present

- name: "Make sure network configuration source interfaces.d/"
  lineinfile:
    dest: /etc/network/interfaces
    line: "source /etc/network/interfaces.d/*"
    state: present
    backup: true
